services:
  backend:
    build: ./crocomoji-backend
    restart: unless-stopped

  frontend:
    build: ./crocomoji-frontend
    volumes:
      - frontend_dist:/dist
    restart: "no"

volumes:
  frontend_dist:
